[build]
  command = "npm install && npx vite build"
  publish = "dist"

# SPA fallback: manda tudo pro index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- HEADERS DE SEGURANÇA ---
[[headers]]
  for = "/*"
  [headers.values]
    # HTTPS-only e proteção contra downgrade
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

    # Mitigações variadas
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Permissões do navegador (só libere o que você usa)
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), fullscreen=(self)"

    # CSP mais permissiva para resolver problemas de React/Recharts
    Content-Security-Policy = '''
      default-src 'self';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';

      connect-src 'self' https://*.supabase.co https://*.supabase.in https://maps.googleapis.com https://servicodados.ibge.gov.br wss://*.supabase.co;
      img-src 'self' data: https://*.googleapis.com https://*.gstatic.com blob:;
      font-src 'self' data: https://*.gstatic.com;
      style-src 'self' 'unsafe-inline';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://maps.googleapis.com https://*.gstatic.com;
      worker-src 'self' blob:;
    '''

# Configurações específicas para Node.js
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configurações de cache
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"