export type LeaderListItem = {
    id: string;
    profile_id: string;
    full_name: string | null;
    email: string | null;
    phone: string | null;
    goal: number | null;
    status: "INVITED" | "PENDING" | "ACTIVE" | "INACTIVE" | null;
    invited_at: string | null;
    accepted_at: string | null;
    is_active: boolean | null;
    is_pending: boolean | null;
    city: string | null;
    state: string | null;
};
export type LeaderDetail = {
    id: string;
    full_name: string | null;
    email: string | null;
    phone: string | null;
    birth_date: string | null;
    gender: "M" | "F" | "O" | null;
    cep: string | null;
    street: string | null;
    number: string | null;
    complement: string | null;
    neighborhood: string | null;
    city: string | null;
    state: string | null;
    notes: string | null;
    goal: number | null;
    status: "PENDING" | "INVITED" | "ACTIVE" | "INACTIVE" | null;
    invited_at: string | null;
    accepted_at: string | null;
    is_active: boolean | null;
    latitude?: number | null;
    longitude?: number | null;
};
export type LeaderInsert = {
    full_name: string;
    email: string;
    phone?: string;
    birth_date?: string;
    gender?: string;
    cep?: string;
    street?: string;
    number?: string;
    complement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    notes?: string;
    latitude?: number | null;
    longitude?: number | null;
};
export declare function listLeaders(): Promise<LeaderListItem[]>;
export declare function getLeaderDetail(id: string): Promise<LeaderDetail & {
    leadership?: any;
}>;
export declare function updateLeaderProfile(id: string, values: Partial<LeaderDetail>): Promise<boolean>;
export declare function createLeader(payload: LeaderInsert): Promise<any>;
export declare function updateLeader(id: string, payload: Partial<LeaderInsert>): Promise<any>;
export declare function inviteLeader(payload: {
    full_name: string;
    email: string;
    phone?: string;
    birth_date?: string;
    gender?: string;
    cep?: string;
    street?: string;
    number?: string;
    complement?: string;
    neighborhood?: string;
    city?: string;
    state?: string;
    notes?: string;
    latitude?: number | null;
    longitude?: number | null;
    appUrl?: string;
}): Promise<any>;
export declare function resendInvite(email: string, full_name?: string): Promise<any>;
export declare function deactivateLeader(id: string): Promise<void>;
export declare const listPendingLeaders: () => Promise<LeaderListItem[]>;
export declare const revokeInvite: (email: string) => Promise<void>;
